cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('increase/<int:id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease/<int:id>/', views.decrease_quantity, name='decrease_quantity'),
    path('remove/<int:id>/', views.remove_item, name='remove_item'),
    path('checkout/', views.checkout, name='checkout')
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    
    def total_price(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return f"{self.product.name} ({self.quantity})"

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import CartItem
from products.models import Product
from django.contrib.auth.decorators import login_required

@login_required
def add_to_cart(request, id):
    product = get_object_or_404(Product, id=id)
    cart_item, created = CartItem.objects.get_or_create(user=request.user, product=product)
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def increase_quantity(request, id):
    item = get_object_or_404(CartItem, id=id, user=request.user)
    item.quantity += 1
    item.save()
    return redirect('cart:cart')

@login_required
def decrease_quantity(request, id):
    item = get_object_or_404(CartItem, id=id, user=request.user)
    if item.quantity > 1:
        item.quantity -= 1
        item.save()
    else:
        item.delete()
    return redirect('cart:cart')

@login_required
def remove_item(request, id):
    item = get_object_or_404(CartItem, id=id, user=request.user)
    item.delete()
    return redirect('cart:cart')

@login_required
def cart_view(request):
    items = CartItem.objects.filter(user=request.user)
    total = sum(item.total_price() for item in items)
    return render(request, 'cart.html', {'items': items, 'total': total})


@login_required
def checkout(request):
    items = CartItem.objects.filter(user=request.user)
    total = sum(item.total_price() for item in items)

    return render(request, 'checkout.html', {
        'items': items,
        'total': total
    })

cart/templates/cart.html
{% extends "base.html" %}
{% block content %}
<h2 class="text-2xl font-bold mb-4 text-center">Your Cart</h2>

{% if items %}
<table class="w-full border-collapse border">
  <thead>
    <tr class="bg-gray-100 border-b">
        <th class="p-2">Image</th>
      <th class="p-2 text-left">Product</th>
      <th class="p-2">Quantity</th>
      <th class="p-2">Price</th>
      <th class="p-2">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr class="border-b">
      <td class="p-2">
        <img src="{{ item.product.main_image.url}}" alt="{{item.product.name}}" class="h-10 w-10 md:h-20 md:w-20">
      </td>
      <td class="p-2"><p class="line-clamp-2 text-xs md:text-sm">
        {{ item.product.name }}
      </p></td>
      <td class="p-2 flex items-center gap-1">
        <a href="{% url 'cart:decrease_quantity' item.id %}" class="px-2 bg-gray-200 rounded">-</a>
        <span class="px-2">{{ item.quantity }}</span>
        <a href="{% url 'cart:increase_quantity' item.id %}" class="px-2 bg-gray-200 rounded">+</a>
      </td>
      <td class="p-2">₹{{ item.total_price }}</td>
      <td class="p-2">
        <a href="{% url 'cart:remove_item' item.id %}" class="text-red-500 hover:underline">Remove</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


<h3 class="text-right mt-4 text-xl font-bold">Total: ₹{{ total }}</h3>

<div class="max-w-md">
  <a href="{% url 'cart:checkout' %}" class="bg-amber-600 px-3 py-1 text-white text-center">Checkout</a>
</div>

{% else %}
<p class="text-center mt-6">Your cart is empty.</p>
{% endif %}


{% endblock %}