cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('increase/<int:id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease/<int:id>/', views.decrease_quantity, name='decrease_quantity'),
    path('remove/<int:id>/', views.remove_item, name='remove_item'),
    path('checkout/', views.checkout, name='checkout')
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="shortcut icon" href="https://tse2.mm.bing.net/th/id/OIP.O5ip3Cal9h_8WUar84JeMAHaFP?pid=Api&P=0&h=180" type="image/x-icon">
    <title>{% block title %}
        Ecommerce - Buy dress, shoes, and accessories for daily life style.
        {% endblock %}</title>
</head>

    <header class="bg-green-700 shadow flex justify-between items-center p-2 md:px-15 lg:px-30">
        <a href="/" class="font-semibold text-white text-lg md:text-xl">Ecomm</a>

        <form 
        method="GET" 
        action="{% url 'product_search' %}" 
        class="w-24 sm:w-40 md:w-56 lg:w-80"
        >
        <input 
        type="text" 
        name="q" 
        placeholder="Search products..." 
        class="w-full px-2 py-1 text-xs sm:text-sm md:text-lg bg-white text-black rounded outline-none"
        >
        </form>


        <nav class="flex gap-1 items-center">
            {% if user.is_authenticated %}
            <div class="text-white font-semibold text-xs flex flex-col"><img src="https://th.bing.com/th/id/OIP.w2McZSq-EYWxh02iSvC3xwHaHa?w=198&h=198&c=7&r=0&o=7&cb=ucfimg2&dpr=1.3&pid=1.7&rm=3&ucfimg=1" class="h-8 w-8 rounded-full"> Hi, {{user.first_name}}</div>
            <a href="{% url 'logout'%}" class="bg-red-500 hover:bg-red-600 hover:cursor-pointer text-white px-2 py-1 rounded text-[12px] md:text-sm">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="bg-green-400 text-white px-2 py-1 rounded hover:cursor-pointer hover:bg-green-500 text-[12px] md:text-sm">Login</a>
            <a href="{% url 'signup' %}" class="bg-red-500 text-white px-2 py-1 rounded hover:cursor-pointer hover:bg-red-600 text-[12px] md:text-sm">Signup</a>
            {% endif %}
            <a href="{% url 'cart:cart' %}" class="bg-blue-500 text-white px-2 py-1 rounded hover:cursor-pointer hover:bg-blue-600 text-[12px] flex flex-col md:text-sm relative">
                
                Cart
                {% if cart_count > 0 %}
                 <span class="absolute top-0 right-0 inline-block w-5 h-5 text-xs font-semibold text-white bg-red-500 rounded-full text-center">
                    {{cart_count}}
                 </span>
                {% endif %}
            </a>
        </nav>
    </header>

    <div class="p-2 md:px-15 lg:px-30">
        {% block content %}{% endblock %}
    </div>
    


</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

<h2 class="text-xl text-center mb-4">Products</h2>

<div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">

{% for product in products %}
  <div class="bg-white shadow rounded p-2 relative">

    <a href="{% url 'product_detail' product.id %}">
      <img src="{{ product.main_image.url }}" class="h-40 mx-auto mb-2">
      <h3 class="text-sm line-clamp-2">{{ product.name }}</h3>
      <p class="font-bold">₹{{ product.price }}</p>
    </a>

    {% if not request.user.is_authenticated %}
      <!-- NOT LOGGED IN -->
      <a href="{% url 'login' %}"
         class="block mt-2 bg-blue-600 text-white text-center py-2 rounded">
        Login to Add
      </a>

    {% else %}
      <!-- LOGGED IN -->
      {% with qty=0 %}
        {% for item in cart_items %}
          {% if item.product.id == product.id %}
            {% with qty=item.quantity %}
            {% endwith %}
          {% endif %}
        {% endfor %}

        {% if qty > 0 %}
          <div class="mt-2 bg-green-700 text-white text-center py-2 rounded">
            In Cart: {{ qty }}
          </div>
        {% else %}
          <a href="{% url 'cart:add_to_cart' product.id %}"
             class="block mt-2 bg-green-700 text-white text-center py-2 rounded">
            Add to Cart
          </a>
        {% endif %}
      {% endwith %}
    {% endif %}

  </div>
{% endfor %}

</div>

{% endblock %}